---
title: "BLS Dyslexia"
author: "IM/EC"
format: html
editor: visual
---

## Quarto

## Running Code


```{r load_data, include=FALSE}
source("data/load-project-data.R")

project_data_full <- project_data %>% 
  filter(academic_year == "2023-2024") %>%
  left_join( project_data %>% 
  filter(academic_year == "2022-2023") %>% 
    select(-academic_year,
    -first_name,
    -last_name,
    -sped,
    -grade_level_id,
    -school_number,
    -is_csi,
    -grade_level_display,
    -school_name,
    -region_name,
    -teacher_email,
    -in_program) %>%
    setNames(paste0('2022_2023_', names(.))) %>%
    rename(student_number = `2022_2023_student_number`), join_by(student_number)) %>%
  mutate(grade_equivalent_renstar_growth = grade_equivalent_renstar_eoy - grade_equivalent_renstar_boy,
         `2022_2023_grade_equivalent_renstar_growth` = `2022_2023_grade_equivalent_renstar_eoy` - `grade_equivalent_renstar_boy`)

write.csv(project_data_full, "data/project_data_full.csv")
  

```



```{r ge_renstar_eoy}

library(MatchIt)
library("marginaleffects")

matchit_data_ge_eoy <- project_data_full %>%
  filter(!is.na(`2022_2023_grade_equivalent_renstar_eoy`),
         !is.na(grade_equivalent_renstar_eoy))

matchit_check <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_eoy` + grade_equivalent_renstar_eoy, 
                    data = matchit_data_ge_eoy, method = NULL, distance = "glm")

summary(matchit_check)



matchit_match <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name +
                    `2022_2023_grade_equivalent_renstar_eoy` + grade_equivalent_renstar_eoy,
                    data = matchit_data_ge_eoy, method = "nearest", distance = "glm")


summary(matchit_match)

plot(summary(matchit_match))

plot(matchit_match, type = "jitter", interactive = FALSE)

plot(matchit_match, type = "density", interactive = FALSE,
     which.xs = ~ grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_eoy`)



matchit_matched_data <- match.data(matchit_match)

fit <- lm(grade_equivalent_renstar_eoy ~ in_program * (grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_eoy`), data = matchit_matched_data, 
          weights = weights)

effects <- avg_comparisons(fit,
                variables = "in_program",
                vcov = ~subclass,
                newdata = subset(matchit_matched_data, in_program == 1),
                wts = "weights")

effects


```


```{r ge_renstar_growth}

library(MatchIt)
library("marginaleffects")

matchit_data_ge_eoy <- project_data_full %>%
  filter(!is.na(`2022_2023_grade_equivalent_renstar_growth`),
         !is.na(grade_equivalent_renstar_growth))

matchit_check <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_growth` + grade_equivalent_renstar_growth, 
                    data = matchit_data_ge_eoy, method = NULL, distance = "glm")

summary(matchit_check)



matchit_match <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name +
                    `2022_2023_grade_equivalent_renstar_growth` + grade_equivalent_renstar_growth,
                    data = matchit_data_ge_eoy, method = "nearest", distance = "glm")


summary(matchit_match)

plot(summary(matchit_match))

plot(matchit_match, type = "jitter", interactive = FALSE)

plot(matchit_match, type = "density", interactive = FALSE,
     which.xs = ~ grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_growth`)



matchit_matched_data <- match.data(matchit_match)

fit <- lm(grade_equivalent_renstar_growth ~ in_program * (grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_growth`), data = matchit_matched_data, 
          weights = weights)

effects <- avg_comparisons(fit,
                variables = "in_program",
                vcov = ~subclass,
                newdata = subset(matchit_matched_data, in_program == 1),
                wts = "weights")

effects

```
```{r star_level_current_renstar_boy}

library(MatchIt)
library("marginaleffects")

matchit_data_star_level <- project_data_full %>%
  filter(!is.na(grade_equivalent_renstar_boy),
         !is.na(staar_score_staar_reading))

matchit_check <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name + 
                    grade_equivalent_renstar_boy + staar_score_staar_reading, 
                    data = matchit_data_star_level, method = NULL, distance = "glm")

summary(matchit_check)



matchit_match <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name +
                    grade_equivalent_renstar_boy + staar_score_staar_reading,
                    data = matchit_data_star_level, method = "nearest", distance = "glm")


summary(matchit_match)

plot(summary(matchit_match))

plot(matchit_match, type = "jitter", interactive = FALSE)

plot(matchit_match, type = "density", interactive = FALSE,
     which.xs = ~ grade_level_id + sped + is_csi + region_name + 
                    grade_equivalent_renstar_boy)



matchit_matched_data <- match.data(matchit_match)

fit <- lm(staar_score_staar_reading ~ in_program * (grade_level_id + sped + is_csi + region_name + 
                    grade_equivalent_renstar_boy), data = matchit_matched_data, 
          weights = weights)

effects <- avg_comparisons(fit,
                variables = "in_program",
                vcov = ~subclass,
                newdata = subset(matchit_matched_data, in_program == 1),
                wts = "weights")

effects

```

```{r star_level_previous_renstar_boy}

library(MatchIt)
library("marginaleffects")

matchit_data_star_level <- project_data_full %>%
  filter(!is.na(`2022_2023_grade_equivalent_renstar_boy`),
         !is.na(staar_score_staar_reading))

matchit_check <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_boy` + staar_score_staar_reading, 
                    data = matchit_data_star_level, method = NULL, distance = "glm")

summary(matchit_check)



matchit_match <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name +
                    `2022_2023_grade_equivalent_renstar_boy` + staar_score_staar_reading,
                    data = matchit_data_star_level, method = "nearest", distance = "glm")


summary(matchit_match)

plot(summary(matchit_match))

plot(matchit_match, type = "jitter", interactive = FALSE)

plot(matchit_match, type = "density", interactive = FALSE,
     which.xs = ~ grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_boy`)



matchit_matched_data <- match.data(matchit_match)

fit <- lm(staar_score_staar_reading ~ in_program * (grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_boy`), data = matchit_matched_data, 
          weights = weights)

effects <- avg_comparisons(fit,
                variables = "in_program",
                vcov = ~subclass,
                newdata = subset(matchit_matched_data, in_program == 1),
                wts = "weights")

effects

```
```{r staar_progress}

library(MatchIt)
library("marginaleffects")

matchit_data_staar_level <- project_data_full %>%
  filter(!is.na(progress_measure_staar_reading),
         !is.na(grade_equivalent_renstar_boy))

matchit_check <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name + 
                    progress_measure_staar_reading + grade_equivalent_renstar_boy, 
                    data = matchit_data_staar_level, method = NULL, distance = "glm")

summary(matchit_check)



matchit_match <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name +
                    progress_measure_staar_reading + grade_equivalent_renstar_boy,
                    data = matchit_data_staar_level, method = "nearest", distance = "glm")


summary(matchit_match)

plot(summary(matchit_match))

plot(matchit_match, type = "jitter", interactive = FALSE)

plot(matchit_match, type = "density", interactive = FALSE,
     which.xs = ~ grade_level_id + sped + is_csi + region_name + 
                    grade_equivalent_renstar_boy)



matchit_matched_data <- match.data(matchit_match)

fit <- lm(progress_measure_staar_reading ~ in_program * (grade_level_id + sped + is_csi + region_name + 
                    grade_equivalent_renstar_boy), data = matchit_matched_data, 
          weights = weights)

effects <- avg_comparisons(fit,
                variables = "in_program",
                vcov = ~subclass,
                newdata = subset(matchit_matched_data, in_program == 1),
                wts = "weights")

effects
```

```{r in_program_current_vs_previous}

library(ggplot2)

in_program_current_vs_previous <- project_data %>%
  mutate(grade_equivalent_renstar_growth = grade_equivalent_renstar_eoy - grade_equivalent_renstar_boy) %>%
  filter(!is.na(grade_equivalent_renstar_growth)) %>%
  filter(in_program == 1) 

  
print(summary(in_program_current_vs_previous))

hist(in_program_current_vs_previous$grade_equivalent_renstar_growth)

ggplot(data=in_program_current_vs_previous, aes(x=grade_level_id, y=grade_equivalent_renstar_boy, fill=academic_year)) +
geom_bar(aes(x=grade_level_id, y=grade_equivalent_renstar_boy, fill=as.factor(academic_year)), stat="summary", position = "dodge",  fun.y = "mean")


```


```{r graph_model_star_level_renstar_previous_boy}


library(MatchIt)
library("marginaleffects")

matchit_data_star_level <- project_data_full %>%
  filter(!is.na(`2022_2023_grade_equivalent_renstar_boy`),
         !is.na(staar_score_staar_reading))


matchit_match <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name +
                    `2022_2023_grade_equivalent_renstar_boy` + staar_score_staar_reading,
                    data = matchit_data_star_level, method = "nearest", distance = "glm")


summary(matchit_match)

plot(summary(matchit_match))

plot(matchit_match, type = "jitter", interactive = FALSE)

plot(matchit_match, type = "density", interactive = FALSE,
     which.xs = ~ grade_level_id + sped + is_csi + region_name + 
                    `2022_2023_grade_equivalent_renstar_boy`)



matchit_matched_data <- match.data(matchit_match)

matchit_matched_data %>%
  mutate(in_program = if_else(in_program == 1, "In Program", "Not In Program"),
         in_program = as.factor(in_program)) %>%
ggplot(aes(x=in_program, y=staar_score_staar_reading, fill=in_program)) +
geom_bar(aes(x=in_program, y=staar_score_staar_reading, fill=as.factor(in_program)), stat="summary", position = "dodge",  fun.y = "mean")

matchit_matched_data %>%
  mutate(in_program = if_else(in_program == 1, "In Program", "Not In Program"),
         in_program = as.factor(in_program),
         staar_score_staar_reading_text = case_when(staar_score_staar_reading == 0 ~ "Did Not Meet",
                                                    staar_score_staar_reading == 1 ~ "Approaches",
                                                    staar_score_staar_reading == 2 ~ "Meets",
                                                    staar_score_staar_reading == 3 ~ "Masters",
                                                    TRUE ~ NA)) %>%
ggplot(aes(x=in_program, y=staar_score_staar_reading)) +
geom_count(aes(x=in_program, color=after_stat(n), size = after_stat(n))) +
  guides(color = 'legend')

t.test(matchit_matched_data$staar_score_staar_reading)

```

```{r graph_model_star_level_renstar_current_boy}


library(MatchIt)
library("marginaleffects")

matchit_data_star_level <- project_data_full %>%
  filter(!is.na(grade_equivalent_renstar_boy),
         !is.na(staar_score_staar_reading))


matchit_match <- matchit(in_program ~ grade_level_id + sped + is_csi + region_name +
                    grade_equivalent_renstar_boy + staar_score_staar_reading,
                    data = matchit_data_star_level, method = "nearest", distance = "glm")


summary(matchit_match)

plot(summary(matchit_match))

plot(matchit_match, type = "jitter", interactive = FALSE)

plot(matchit_match, type = "density", interactive = FALSE,
     which.xs = ~ grade_level_id + sped + is_csi + region_name + 
                    grade_equivalent_renstar_boy)



matchit_matched_data <- match.data(matchit_match)


ggplot(data=matchit_matched_data, aes(x=in_program, y=staar_score_staar_reading, fill=in_program)) +
geom_bar(aes(x=in_program, y=staar_score_staar_reading, fill=as.factor(in_program)), stat="summary", position = "dodge",  fun.y = "mean")

t.test(matchit_matched_data$staar_score_staar_reading)

```